### ISSUE TITLE
Investigate failing SELECT queries (with bitwise operators) 

### ISSUE THREAD

**Issue by ErikEJ** [GibraltarSoftware/VistaDB.EFCore#11]
.Where_bitwise_and()

```
  SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
  FROM [Customers] AS [c]
  WHERE (CASE
      WHEN [c].[CustomerID] = N'ALFKI'
      THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
  END & CASE
      WHEN [c].[CustomerID] = N'ANATR'
      THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
  END) = 1
  
  An exception occurred in the database while iterating the results of a query for context type 'Microsoft.EntityFrameworkCore.TestModels.Northwind.NorthwindRelationalContext'.
  VistaDB.Diagnostic.VistaDBSQLException (0x0000022E): 
  Error 558 (Provider v. 5.6.8.0): Invalid operand(s) data type for operator:  &
  Line #: 6; Column #: 5
  Error 558 (Provider v. 5.6.8.0): Invalid operand(s) data type for operator:  &
  Line #: 6; Column #: 5
   ---> VistaDB.Diagnostic.VistaDBSQLException (0x0000022E): 
  Error 558 (Provider v. 5.6.8.0): Invalid operand(s) data type for operator:  &
  Line #: 6; Column #: 5
  
     at VistaDB.Engine.SQL.Signatures.ConstantSignature.PrepareBinaryOperator(Signature& leftOperand, Signature& rightOperand, VistaDBType& dataType, Boolean mustBeNumeric, Boolean maxNumeric, String text, Int32 lineNo, Int32 symbolNo)
     at VistaDB.Engine.SQL.Signatures.BitwiseAndOperator.OnPrepare()
     at VistaDB.Engine.SQL.Signatures.ConstantSignature.PrepareBinaryOperator(Signature& leftOperand, Signature& rightOperand, VistaDBType& dataType, Boolean mustBeNumeric, Boolean maxNumeric, String text, Int32 lineNo, Int32 symbolNo)
     at VistaDB.Engine.SQL.Signatures.BinaryCompareOperator.OnPrepare()
     at VistaDB.Engine.SQL.Signatures.EqualOperator.OnPrepare()
     at VistaDB.Engine.SQL.BaseSelectStatement.WhereClause.Prepare()
     at VistaDB.Engine.SQL.SelectStatement.OnPrepareQuery()
     at VistaDB.Engine.SQL.Statement.PrepareQuery()
     at VistaDB.Engine.SQL.Statement.ExecuteQuery()
     at VistaDB.Engine.SQL.BatchStatement.NextResult(VistaDBPipe pipe)
     at VistaDB.Engine.SQL.BatchStatement.CheckBatchExceptions()
     at VistaDB.Engine.SQL.BatchStatement.NextResult(VistaDBPipe pipe)
     at VistaDB.Provider.VistaDBDataReader.GoNextResult()
     at VistaDB.Provider.VistaDBDataReader..ctor(IQueryStatement statement, VistaDBConnection connection, CommandBehavior commandBehavior)
     at VistaDB.Provider.VistaDBCommand.ExecuteReader(CommandBehavior behavior)
     at VistaDB.Provider.VistaDBCommand.ExecuteDbDataReader(CommandBehavior behavior)

```

**Comment by rparker-gibraltar** [comment]
Hmmm, looking at the engine code, it looks like BIT is not being considered a numeric type, so the type (for the binary operator) is likely falling back to the default numeric type (FLOAT) which of course can't do bitwise-and (also has no cross-conversion with BIT, which is what triggers the specific rejection in the error above).

It wouldn't be hard to add BIT to the list of "numeric types" which might allow fixing the bitwise-and of BIT types, but there could be other unexpected implications of making that change, so I'll need to research what else it might affect.  Internally, VistaDB handles BIT as bool, which isn't exactly a number.  But this is an area of inconsistency we have vs. SQL Server which might be worth trying to fix more comprehensively (but maybe not so easily).

**Comment by rparker-gibraltar** [comment]
By the way, the construct of using a CASE in a WHERE clause will tend to break the optimizer's ability to recognize and apply a filter for the conditions.  Logically combining the comparisons directly in the WHERE clause would tend to work better in VistaDB.

Also, it seems like that example would always result in empty results since [c].[CustomerId] can't equal two different string values--but maybe that's an intentional part of the test?
